@url_dev=http://localhost:3000/v1/api

### SIGN UP
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key : 1ebedd8911d3e3b745ab8be9f23d13ed85f94d7dab06ea2005a7d7d37c7d13fbfc811e2370f767a806437cfa69f206cc214aafb6b3e3960debada2f171d47e32

{
    "name": "Shop Panda",
    "email": "pandaShop02@gmail.com",
    "password": "123456"
}

### LOGIN
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key : 1ebedd8911d3e3b745ab8be9f23d13ed85f94d7dab06ea2005a7d7d37c7d13fbfc811e2370f767a806437cfa69f206cc214aafb6b3e3960debada2f171d47e32

{
    "email": "pandaShop02@gmail.com",
    "password": "123456"
}

### LOGOUT
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key : 1ebedd8911d3e3b745ab8be9f23d13ed85f94d7dab06ea2005a7d7d37c7d13fbfc811e2370f767a806437cfa69f206cc214aafb6b3e3960debada2f171d47e32
x-client-id: 686b74e33c02f2cf1117a6f9
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2ODZiNzRlMzNjMDJmMmNmMTExN2E2ZjkiLCJlbWFpbCI6InBhbmRhU2hvcDAyQGdtYWlsLmNvbSIsImlhdCI6MTc1MTg3MjgwNCwiZXhwIjoxNzUyMDQ1NjA0fQ.PcDMXnV9oyVokiJjfcdHsUuxS_orv0bJWIO8xHe-RAE

### REFRESH TOKEN
POST {{url_dev}}/shop/refresh-token
Content-Type: application/json
x-api-key : 1ebedd8911d3e3b745ab8be9f23d13ed85f94d7dab06ea2005a7d7d37c7d13fbfc811e2370f767a806437cfa69f206cc214aafb6b3e3960debada2f171d47e32
x-client-id: 686b74e33c02f2cf1117a6f9
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2ODZiNzRlMzNjMDJmMmNmMTExN2E2ZjkiLCJlbWFpbCI6InBhbmRhU2hvcDAyQGdtYWlsLmNvbSIsImlhdCI6MTc1MTk1Mjg4OCwiZXhwIjoxNzUyNTU3Njg4fQ.Y73dKFCs_qI75JZQJhYd_u6-X2kOQpZHz4gfCFddpN4

